language: node_js

os:
  - linux

jobs:
  include:
    - stage: Testing (node 12)
      node_js: 12
      if: type = pull_request
      before_script:
        - npm run lint
      install:
        - npm install
      script:
        - npm run test
    - stage: Testing (node 10)
      node_js: 10
      if: type = pull_request
      before_script:
        - npm run lint
      install:
        - npm install
      script:
        - npm run test
    - stage: Testing (node 8)
      node_js: 8
      if: type = pull_request
      before_script:
        - npm run lint
      install:
        - npm install
      script:
        - npm run test    
    - stage: release
      node_js: 12
      if: branch = master AND type = push
      script: skip
      deploy:
        provider: script
        cleanup: true
        script: npm install && npm run build && npm run semantic-release
